AllCops:
    NewCops: enable
    SuggestExtensions: false
    Exclude:
    - './bin/*'
    - './config/*'
    - 'db/seeds.rb'

Style/MethodDefParentheses:
    Enabled: false

Naming/MemoizedInstanceVariableName:
    Enabled: false

Layout/SpaceInsideStringInterpolation:
    Enabled: false
